baseURL: https://diglog.io
languageCode: en-us
title: Diglog
theme: "PaperMod"
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-EF0JZGXEF6

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Diglog
  description: "Personal blog"
  author: Hyeongbin Kim
  images: ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: true
  hidemeta: false
  showtoc: true
  tocopen: false
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon.png"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Diglog
    subtitle: "Planning to write some notes on what I am working on"
    imageUrl: "/logo.gif"
    imageWidth: 150
    imageHeight: 150
    imageTitle: my image
    buttons:
      - name: About Me
        url: "/about/"
      - name: Archive
        url: "/archives"

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/hbinkim"
    - name: linkedin
      url: "https://www.linkedin.com/in/hyeongbinkim/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Archive
      url: /archives/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - name: Search
      url: /search/
      weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
